[workspace]
members = [
    "c2rust",
    "c2rust-transpile",
    "c2rust-ast-builder",
    "c2rust-ast-exporter",
    "c2rust-ast-printer",
    "c2rust-bitfields",
    "c2rust-macros",
    "c2rust-asm-casts",
    "analysis/runtime",
    "dynamic_instrumentation",
    "pdg"
]
exclude = [
    "cross-checks/pointer-tracer",
    "cross-checks/zero-malloc",
    "cross-checks/rust-checks",
    "examples",
    "analysis/test",
    "tests",
]

[profile.dev.package."*"]
opt-level = 3
